--CRIANDO UMA NOVA TABLESPACE
CREATE TABLESPACE PROJETO_PET
    DATAFILE 
        'C:\oraclexe\app\oracle\oradata\XE\PROJETO_PET.DBF'
        SIZE 100M AUTOEXTEND ON NEXT 50M MAXSIZE 500M
        ONLINE
        EXTENT MANAGEMENT LOCAL AUTOALLOCATE
        SEGMENT SPACE MANAGEMENT AUTO;

--CRIANDO UM USUÁRIO
CREATE USER DESENVOLVEDOR
    IDENTIFIED BY DESENVOLVEDOR
    DEFAULT TABLESPACE PROJETO_PET
    TEMPORARY TABLESPACE TEMP;

--PERMISSAO PARA O USUARIO
GRANT CREATE SESSION, CONNECT, RESOURCE TO DESENVOLVEDOR;
ALTER USER DESENVOLVEDOR QUOTA UNLIMITED ON PROJETO_PET;

--DELETAR O USUARIO (NAO EXECUTEI APENAS PARA GUARDAR)
DROP USER DESENVOLVEDOR;

--DELETAR O TABLESPACE (NAO EXECUTEI APENAS PARA GUARDAR)
DROP TABLESPACE PROJETO_PET
    INCLUDING CONTENTS AND DATAFILES
        CASCADE CONSTRAINTS;